### PR TITLE
Syntax Highlighting

### PR DESCRIPTION
**Pull request by GrimTheReaper**
Added proper markdown for github to color the Golang syntax.

### CODE REVIEW

**Comment by mariussturm** [comment]
Hi,
thanks for the PR. Is the changed indentation neccessary for the highlighting or is `'''go` sufficient?

**Comment by GrimTheReaper** [comment]
```go

**Comment by GrimTheReaper** [comment]
@mariussturm the reason for the changed indentation is because the previous indentation marked it as code, and changing it over to ` ```go ` takes it as raw. Without the changed indentations the code would be indented out, rather than at the beginning of the line.

Thank you for merging my PR.

**Comment by bangert** [comment]
i think this was only committed to the v1 branch. master and v2 could use this change as well...

**Pull request merged**
